os: linux
dist: focal
language: cpp

install:
 - sudo apt-get update
 - sudo apt-get install --yes libgtest-dev
 - sudo apt-get install --yes cmake
 - sudo apt-get install --yes gcovr
jobs:
 - stage: Build
   script:
    - cmake -B build -DCMAKE_BUILD_TYPE=Release
    - make -C build
 - stage: Test
   script:
    - cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=1
    - make -C build
    - ctests --test-dir build --output-on-failure
 - stage: TestCoverage
   script:
    - cmake -B build -DCMAKE_BUILD_TYPE=Debug -DWITH_COVERAGE=1
    - make -C build all test
    - gcovr 
    - bash <(curl -s https://codecov.io/bash)
 - stage: Sanitaize
   script:
    - cmake -B build -DCMAKE_BUILD_TYPE=Debug -DWITH_SANITIZERS=1
    - make -C build
    - ctests --test-dir build --output-on-failure
